# Copyright 2025 Jab125
# This file is part of Discord-Social-SDK4J.
# Discord-Social-SDK4J is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# Discord-Social-SDK4J is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along with Discord-Social-SDK4J. If not, see <https://www.gnu.org/licenses/>.
name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: install libsound2, libatomic1, and libpulse0
        run: sudo apt-get update && sudo apt-get install libasound2t64 libatomic1 libpulse0 -y
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: test
        run: ./gradlew test
        env:
          secretSauce: ${{ secrets.SECRET_SAUCE }}